package com.river.engine.ast.operands.metric;

import lombok.Data;

import java.io.Serializable;

/**
 * @author Juyony Chen
 * @version 1.0.0, 2020/9/16 18:28
 * @since 1.0.0, 2020/9/16 18:28
 **/
@Data
public class MetricMessage implements Serializable {
    private static final long serialVersionUID = 9181912841018894150L;

    /**
     * A unique metric id generated by snowflake policy
     */
    private long id;

    /**
     */
    private String message;



    public MetricMessage(String message){
        this.message = message;
    }

    public MetricMessage(long id, String message){
        this.message = message;
        this.id = id;
    }

}
